version: "3.7"
volumes:
  webroot:
    driver: local
services:
  php:
    image: srvaudit/dnsape-php:1.1
    volumes:
      - /data/log/dnsape.log:/usr/src/dnsape/storage/logs/laravel.log
  web:
    image: srvaudit/dnsape-web:1.1
    volumes:
      - webroot:/var/www/dnsape/public
      - /data/certs:/etc/nginx/ssl
    ports:
      - mode: host
        target: 443
        published: 443
        protocol: tcp
      - mode: host
        target: 80
        published: 80
        protocol: tcp
